### ISSUE TITLE
Use rollup-plugin-base64

### ISSUE THREAD

**Issue by gzuidhof** [manzt/numcodecs.js#8]
I started playing with WASM a bit more lately, and also ran into the problem of shipping the WASM source embedded in code.

I created a simple rollup plugin called [**`rollup-plugin-base64`**](https://github.com/gzuidhof/rollup-plugin-base64) to embed the base64 of a (wasm) file into your code, this should simplify your current build step. Maybe it's worth considering here :)

It's not published on NPM yet (the name of the package triggered a spam filter, I expect their support will whitelist it soon), so you will have to install it through git for now.

**Comment by manzt** [comment]
This is great, thanks! I know `@rollup/plugin-wasm` does something similar, but it ends up instantiating the `WebAssembly` itself as well, and all I really wanted was the `base64` encoding. I suppose I'll need to rework how testing works, but it would be nice not to check-in the base64 encoded `.ts` file.

**Comment by gzuidhof** [comment]
I just created a small tool that I think is a better fit for the usecase here (and my own), it creates ts or js files without needing a bundler to do it. Let me know what you think.

https://github.com/gzuidhof/wasmwrap

**Comment by gzuidhof** [comment]
This article has a small example https://guido.io/posts/embedding-webassembly-in-javascript-without-a-bundler/

**Comment by manzt** [comment]
#18 finally got around to this...
