### ISSUE TITLE
Importing a single codec when using a browser build

### ISSUE THREAD

**Issue by jbms** [manzt/numcodecs.js#9]
From node.js it is possible to import just a single codec, but this does not seem to work from a browser-targeted build using typescript/webpack.  Typescript gives the error:

```typescript
import {Blosc} from 'numcodecs/blosc';
```

```
Cannot find module 'numcodecs/blosc' or its corresponding type declarations.
```

Using

```typescript
import {Blosc} from 'numcodecs';
```

works but also pulls in pako, which increases the bundle size a fair bit.

**Comment by manzt** [comment]
Hi, thanks for opening the issue. Yes, Node's conditional exports are not well supported by blunders currently (unfortunately). There is an issue here fore [rollup](https://github.com/rollup/plugins/issues/362), but it seems like it's landed in Webpack 5 from what I've been able to find. 

Each codec is bundled separately using code splitting, and is the **default** export from module, so the import shouldn't have the brackets.

```javascript
import Blosc from 'numcodecs/blosc';
// not { Blosc }
```

However, if you are using a webpack, it shouldn't have a hard time tree-shaking what you have. The main entry point is just exporting each of the separate codecs as named exports:

https://github.com/manzt/numcodecs.js/blob/9a3be86dba899c65bc791c2d3b138fc6f755723c/src/index.ts#L1-L4

**Comment by manzt** [comment]
If you continue to have issues with configuring webpack, you can import the esm module for blosc directly:

```javascript
import Blosc from './node_modules/numcodecs/dist/blosc.mjs';
```
